services:
  - type: web
    name: industry-link-portal
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: PORT=10000 npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: smart_institute_j047
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: AWS_REGION
        value: us-east-1
      - key: STORAGE_TYPE
        value: s3
      - key: AWS_S3_BUCKET_NAME
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: "SmartInstitute <skvora1803@gmail.com>"
      - key: REQUIRE_EMAIL_VERIFICATION
        value: true
      - key: BASE_URL
        sync: false
      - key: APP_URL
        sync: false

databases:
  - name: smart_institute_j047
    databaseName: smart_institute_j047
    user: smart_institute_j047_user
    plan: free 